# Generated by Django 4.2.6 on 2023-11-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_modelexecution_paststockmetric_playlist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="playlist",
            name="user",
            field=models.CharField(max_length=120),
        ),
    ]
