# Generated by Django 5.0.1 on 2024-01-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_playlist_id_alter_playlist_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalIndicators",
            fields=[
                (
                    "stock_symbol",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                (
                    "ten_day_closing_sma",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                (
                    "fifty_day_closing_sma",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                (
                    "twohundred_day_closing_sma",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                (
                    "ten_day_closing_wma",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                (
                    "fifty_day_closing_wma",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                (
                    "twohundred_day_closing_wma",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                (
                    "ten_day_closing_ema",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                (
                    "fifty_day_closing_ema",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                (
                    "twohundred_day_closing_ema",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                (
                    "twohundred_day_volume_sma",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                (
                    "fourteen_day_rsi",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                (
                    "twenty_day_cci",
                    models.DecimalField(decimal_places=8, max_digits=16),
                ),
                ("fast_k", models.DecimalField(decimal_places=8, max_digits=16)),
                ("slow_k", models.DecimalField(decimal_places=8, max_digits=16)),
                ("fast_d", models.DecimalField(decimal_places=8, max_digits=16)),
                ("slow_d", models.DecimalField(decimal_places=8, max_digits=16)),
                ("macd", models.DecimalField(decimal_places=8, max_digits=16)),
            ],
        ),
        migrations.AddConstraint(
            model_name="technicalindicators",
            constraint=models.UniqueConstraint(
                fields=("stock_symbol", "date"),
                name="unique_daily_stock_technical_indicators",
            ),
        ),
    ]
